# Generated by Django 3.1.7 on 2021-03-17 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('limit_price', models.FloatField(blank=True, null=True)),
                ('side', models.IntegerField(choices=[(1, 'buy'), (2, 'sell')])),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
