# Generated by Django 3.1.7 on 2021-03-18 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('limit_price', models.FloatField(default=0.0, null=True)),
                ('side', models.CharField(blank=True, choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=4)),
                ('valid_until', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
