# Generated by Django 3.1.7 on 2021-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='limit_price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='valid_until',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
