# Generated by Django 3.1.7 on 2021-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210318_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(blank=True, choices=[('buy', 'buy'), ('sell', 'sell')], max_length=5),
        ),
    ]
